name: Build and install.

# Controls when the action will run.
on:
  # Any change aimed at master.
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel.
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # Ideally I want to use this pre-built docker from GitHub:
    # px4io/px4-dev-simulation-focal
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Run installation scripts.
    - run: 'cd ${GITHUB_WORKSPACE}/scripts/install && ./install_all.bash'
    # Run build scripts
    - run: 'cd ${GITHUB_WORKSPACE}/scripts/build && ./build_all.bash'
